version: "3.9"
services:
  mongodb:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - spring-cloud-network
    ports:
      - "27017:27017"

  user-api:
    container_name: user-api
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network
    depends_on:
      - mongodb

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: "27017"
    depends_on:
      - mongodb
    restart: always
    ports:
      - "8888:8081"
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge