version: "3.9"
services:
  user-api:
    container_name: user-api
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=userlist
    networks:
      - spring-cloud-network

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=userlist
      - ME_CONFIG_MONGODB_AUTH_USERNAME=username
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=username
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongodb
    ports:
      - "8888:8081"

networks:
  spring-cloud-network:
    driver: bridge