apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-api-ingress
  namespace: {{.Values.namespace}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: example-host
      http:
        paths:
          - path: /user-api/(.*)
            pathType: Prefix
            backend:
              service:
                name: user-api-service
                port:
                  number: {{.Values.service.port}}