apiVersion: v1
kind: Service
metadata:
  name: user-api-service
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: user-api
  ports:
    - protocol: TCP
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetPort}}